# Generated by Django 5.1.1 on 2024-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("channel_title", models.CharField(max_length=100)),
                ("thumbnail_url", models.URLField()),
                ("view_count", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-view_count"],
            },
        ),
    ]
