# Generated by Django 3.1.12 on 2024-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('app_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name_eng', models.CharField(db_index=True, max_length=200)),
                ('short_description', models.TextField()),
                ('header_image', models.URLField()),
                ('developers', models.CharField(max_length=500)),
                ('publishers', models.CharField(max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('positive_reviews', models.IntegerField(default=0)),
                ('negative_reviews', models.IntegerField(default=0)),
                ('supported_languages', models.TextField()),
                ('pc_requirements', models.JSONField(default=list)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('screenshots', models.JSONField(default=list)),
            ],
        ),
    ]
