# Generated by Django 3.1.12 on 2024-12-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('thumbnails', models.URLField()),
                ('publishedAt', models.DateTimeField(db_index=True)),
                ('channelName', models.CharField(db_index=True, max_length=100)),
                ('channelImage', models.URLField(default='https://example.com/default-image.jpg')),
                ('viewCount', models.BigIntegerField(default=0)),
                ('summary', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube', to='functions.game')),
            ],
        ),
    ]
