# Generated by Django 3.1.12 on 2024-11-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('header_image', models.URLField()),
                ('release_date', models.DateField(null=True)),
                ('developers', models.CharField(max_length=500)),
                ('publishers', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('supported_languages', models.TextField()),
                ('review_summary', models.CharField(max_length=100)),
                ('positive_reviews', models.IntegerField(default=0)),
                ('negative_reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('is_positive', models.BooleanField()),
                ('votes_helpful', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='steam_game.game')),
            ],
        ),
    ]
