# Generated by Django 3.1.12 on 2024-11-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
