# Generated by Django 3.1.12 on 2024-11-23 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steam_game', '0003_auto_20241120_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='price',
            new_name='final_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='review_summary',
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='is_positive',
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='votes_helpful',
        ),
        migrations.AddField(
            model_name='game',
            name='capsule_image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pc_requirements',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamereview',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_keywords', models.JSONField()),
                ('negative_keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_analysis', to='steam_game.game')),
            ],
        ),
    ]
