# Generated by Django 3.1.12 on 2024-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_game', '0004_auto_20241123_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quarter',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
