# Generated by Django 3.1.12 on 2024-11-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_game', '0005_game_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='app_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='review_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='updated_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['app_id', 'name'], name='steam_game__app_id_daefa1_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['created_at'], name='steam_game__created_de8193_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['updated_at'], name='steam_game__updated_690fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='gamereview',
            index=models.Index(fields=['game', 'review_id'], name='steam_game__game_id_c7bbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='gamereview',
            index=models.Index(fields=['game', 'created_at'], name='steam_game__game_id_964ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='gamereview',
            index=models.Index(fields=['game', 'updated_at'], name='steam_game__game_id_867970_idx'),
        ),
    ]
